### ISSUE TITLE
Support for specialized bit_vector

### ISSUE THREAD

**Issue by rob-p** [gmarcais/compact_vector#1]
Hi @gmarcais!

  This is an awesome project :).  I was doing some testing, and I noticed that if you specialize the `get` function for the case where the number of bits per integer is 1, the access is considerably faster.  Basically, this:

```
template<typename IDX, typename W, unsigned int UB>
static IDX get(const W* p, unsigned int b, unsigned int o) {
  static constexpr size_t Wbits  = bitsof<W>::val;
  static constexpr W      ubmask = ~(W)0 >> (Wbits - UB);
  W                       mask   = ((~(W)0 >> (Wbits - b)) << o) & ubmask;
  IDX                     res    = (*p & mask) >> o;
  if(o + b > UB) {
    const unsigned int over  = o + b - UB;
    mask                     = ~(W)0 >> (Wbits - over);
    res                     |= (*(p + 1) & mask) << (b - over);
  }
  if(std::is_signed<IDX>::value && res & ((IDX)1 << (b - 1)))
    res |= ~(IDX)0 << b;

  return res;
}
```

becomes:

```
template<typename IDX, typename W, unsigned int UB>
static IDX get(const W* p, unsigned int b, unsigned int o) {
  static constexpr size_t Wbits  = bitsof<W>::val;
  static constexpr W      ubmask = ~(W)0 >> (Wbits - UB);
  W                       mask   = ((~(W)0 >> (Wbits - b)) << o) & ubmask;
  return  (*p & mask) >> o;
}
```

How difficult would it be to provide a (compile-time) specialization for bit vectors, that uses this implementation of `get` instead of the generic one?

**Comment by gmarcais** [comment]
Thanks.

Right now, the number of bits used by the entries is a run time argument. It probably would make sense to have a version of the class where the number of bits is a compile time argument. I'll look into that.

On the other hand, `std::vector<bool>` is specialized to be bit-packed as well. If you are looking at a bit vector, what does this compact class give you versus `std::vector<bool>`? Multi-threading guarantees?

**Comment by rob-p** [comment]
Well,  I'm actually looking for a general int_vector class.  That is, we have a couple of projects (e.g. [mantis](https://github.com/splatlab/mantis) and [pufferfish](
https://github.com/COMBINE-lab/pufferfish)) where we use [sdsl-lite](https://github.com/simongog/sdsl-lite) almost entirely for their `int_vector` and `bit_vector` classes.  So, while I am interested in the bitvector specialization, we also need packed vectors of e.g. 2-bit numbers, and arbitrary k-bit numbers.  The other thing that we do is build rank and select structures over these --- which means I need direct access to the underlying packed `uint64_t` array.  Both your class and sdsl provide this; not sure about `std::vector<bool>`.  Generally, I'd prefer this to sdsl since we are only using the bit vector class and this is a much lighter dependency (header only).  Also, your class is MIT licensed ;P.

**Comment by rob-p** [comment]
btw --- a version of the class with a static size type (as is possible with sdsl) would be a nice addition.  This makes `compact::vector<uint64_t, 2>` a nice storage container for bit-backed DNA sequences etc.

**Comment by gmarcais** [comment]
I did implement a specialized version when the number of bits used is known at compile time. Try the branch [feature/compile_time_bits](https://github.com/gmarcais/compact_vector/tree/feature/compile_time_bits).

Although the version using compile time bit length is faster than when using run time bit length, it is still slower than `std::vector<bool>`. I still need to double check my optimizations and maybe optimize further.

Look at [tests/bit_vector_speed.cc](https://github.com/gmarcais/compact_vector/blob/feature/compile_time_bits/tests/bit_vector_speed.cc) for a usage example.

**Comment by rob-p** [comment]
Hi @gmarcais,

  Awesome!  So, what I've been experimenting with (that led me to make this request) is over [here](https://github.com/rob-p/rank_speed_test/tree/select-speed).  What I'm finding *so* interesting is how results vary by (1) compiler and (2) what style of loop is used to access the vectors (old `for(size_t i = 0 ...)` vs new `for(auto e : vec)`).  The program [`TestBitVectorImpl.cpp`](https://github.com/rob-p/rank_speed_test/blob/select-speed/src/TestBitvectorImpl.cpp) is used to generate the numbers below.  Here are the quite strange results I get.  I benchmarked the compact vector as well as SDSL-lite's bitvector & int_vector:

### G++ 5.5
```
❯ ./src/test_bv 4000000000

 Dynamically Sized

generating random queries ...filling vectors

sum sdsl (new)
Elapsed time: 5.01278s
Elapsed time: 5.01704s
Elapsed time: 5.01638s

sum sdsl (old)
Elapsed time: 4.22058s
Elapsed time: 4.2002s
Elapsed time: 4.23012s
sum 1 = 380648897

sum compact (new)
Elapsed time: 3.755s
Elapsed time: 3.76492s
Elapsed time: 3.78578s

sum compact (old)
Elapsed time: 4.55238s
Elapsed time: 4.598s
Elapsed time: 4.5533s

sum 2 = 380648897


 Statically Sized

generating random queries ...filling vectors

sum sdsl (new)
Elapsed time: 3.03829s
Elapsed time: 3.04726s
Elapsed time: 3.0276s

sum sdsl (old)
Elapsed time: 3.37473s
Elapsed time: 3.38353s
Elapsed time: 3.36079s
sum 1 = 380648897

sum compact (new)
Elapsed time: 4.2667s
Elapsed time: 4.28688s
Elapsed time: 4.26832s

sum compact (old)
Elapsed time: 3.96036s
Elapsed time: 3.92882s
Elapsed time: 3.94018s

sum 2 = 380648897
```

### Clang 6
```
❯ ./src/test_bv 4000000000
 Dynamically Sized

generating random queries ...filling vectors

sum sdsl (new)
Elapsed time: 5.43516s
Elapsed time: 5.41158s
Elapsed time: 5.44499s

sum sdsl (old)
Elapsed time: 3.92093s
Elapsed time: 4.03932s
Elapsed time: 3.94351s
sum 1 = 380648897

sum compact (new)
Elapsed time: 6.56013s
Elapsed time: 6.56627s
Elapsed time: 6.58457s

sum compact (old)
Elapsed time: 5.05268s
Elapsed time: 5.05812s
Elapsed time: 5.05484s

sum 2 = 380648897


 Statically Sized

generating random queries ...filling vectors

sum sdsl (new)
Elapsed time: 4.27151s
Elapsed time: 4.26009s
Elapsed time: 4.27005s

sum sdsl (old)
Elapsed time: 2.24245s
Elapsed time: 2.24391s
Elapsed time: 2.25872s
sum 1 = 380648897

sum compact (new)
Elapsed time: 6.71919s
Elapsed time: 6.72622s
Elapsed time: 6.70903s

sum compact (old)
Elapsed time: 4.5088s
Elapsed time: 4.51778s
Elapsed time: 4.5227s

sum 2 = 380648897
```

**Comment by rob-p** [comment]
Ok, I tracked down (under GCC to try and keep some sanity) the sources of some differences.  The reason the new style for loop is faster is simply because your iterator increment is much more efficient than the implementation of `operator[]`.  I also tracked down why the static vector seemed not to perform on par with e.g. sdsl-lite.  After absolutely butchering some template code (there is a tremendous amount of redundancy that I am sure can be removed) I accomplished the following:

```
❯ ./src/test_bv 4000000000


 Statically Sized

generating random queries ...filling vectors

sum sdsl (new)
Elapsed time: 3.68238s
Elapsed time: 3.72257s

sum sdsl (old)
Elapsed time: 2.75246s
Elapsed time: 2.66648s
sum 1 = 380648897

sum compact (new)
Elapsed time: 3.04876s
Elapsed time: 3.08482s

sum compact (old)
Elapsed time: 2.65752s
Elapsed time: 2.65984s

sum 2 = 380648897

sum std (new)
Elapsed time: 1.53906s
Elapsed time: 1.57427s

sum std (old)
Elapsed time: 3.71566s
Elapsed time: 3.63912s

sum 3 = 380648897
```

To do this, I had to create variants of all of the iterator classes that *didn't* partially specialize the `BITS` parameter.  Also, I had to create a special case `operator[]` in the `common` iterator trait for `BITS=1`.  One could also create special cases that are considerably faster for `BITS={8,16,32,64}`, as sdsl does.  Anyway, I'll point to the code here after I upload it, but cleaning up my disaster while keeping the basic optimizations gives a very nice speed boost, especially for static element sizes and especially for bit vectors.

Mostly, the changes are in this mess [right here](https://github.com/rob-p/rank_speed_test/blob/select-speed/include/compact_vector/compact_iterator.hpp).

P.S.  Moreover, my optimizations are currently only implemented for `operator[]() const` --- but I don't think that's too much of a problem.

**Comment by gmarcais** [comment]
Yes, there is some redundancy in the definition of the get/set operators. I would love to remove it.

Let me know when your code is in shape.

**Comment by rob-p** [comment]
Ohh, your redundancy is _nothing_ compared to the massive copy and paste I committed.  I'm sure there is a better way to peel the unspecialized classes from your partial specializations, but my meta-programming-fu isn't what it used to be so I have to think about how to reduce the redundancy I added.

**Comment by gmarcais** [comment]
I guess I was missing some bits for the specialization to be chosen. Everything should be in now. Here is what I get with a slightly different version of your program given below (instead of running all test at once, I run one at a time: it's more fare in my opinion).

``` C++
// Compile with:
// g++ -std=c++11 -O3 -I./include -I<path to>/compact_vector/include $(pkg-config --cflags sdsl-lite) src/TestBitvectorImpl.cpp $(pkg-config --libs sdsl-lite) -o test

#include "sdsl/int_vector.hpp"
#include "compact_vector.hpp"
#include "ScopedTimer.hpp"

#include <random>

template <typename T>
void fill(const std::vector<uint64_t>& p, T& v) {
  ScopedTimer t;
  for (auto s : p) {
    v[s] = 1;
  }
}

template <typename T>
size_t sum(T& v) {
  ScopedTimer t;
  size_t tot{0};
  for (const auto &s : v) {
    tot += s;
  }
  return tot;
}

int main(int argc, char* argv[]) {

  if(argc != 3) {
    std::cerr << "Usage: " << argv[0] << " seed which\n";
    return 1;
  }

  const uint32_t seed = atol(argv[1]);
  std::random_device rd;  //Will be used to obtain a seed for the random number engine
  std::mt19937 gen; //Standard mersenne_twister_engine seeded with rd() if given seed is 0
  if(!seed)
    gen.seed(rd());
  else
    gen.seed(seed);

  std::cerr << "generating random queries ...";
    size_t vecLength{4000000000};
  std::uniform_int_distribution<uint64_t> dis(1, vecLength);

  // values near the mean are the most likely
  // standard deviation affects the dispersion of generated values from the mean
  size_t nsamp = 50000000;
  std::vector<uint64_t> samps(nsamp);
  for (size_t i = 0; i < nsamp; ++i) {
    uint32_t start = static_cast<uint32_t>(dis(gen));
    samps[i] = start;
  }

  const unsigned which = atoi(argv[2]);

  size_t t = 0;
  if(which == 0) {
    std::cerr << "filling sdsl\n";
    sdsl::bit_vector bvs(vecLength);
    fill(samps, bvs);
    t = sum(bvs);
  }

  if(which == 1) {
    std::cerr << "filling compact dynamic\n";
    compact::vector<uint64_t> bvc(1,vecLength);
    fill(samps, bvc);
    t = sum(bvc);
  }

  if(which == 2) {
    std::cerr << "filling compact static\n";
    compact::vector<uint64_t, 1> bvc(vecLength);
    fill(samps, bvc);
    t = sum(bvc);
  }

  if(which >= 3) {
    std::cerr << "Invalid test\n";
    return 1;
  }

  std::cerr << "sum = " << t << '\n';

  return 0;
}
```

The timing I get is:

``` Shell
gus@ocean 0 0 ../rank_speed_test% ./test 314159 2
generating random queries ...filling compact static
Elapsed time: 0.818489s
Elapsed time: 5.08016s
sum = 49688700
./test 314159 2  6.98s user 0.18s system 99% cpu 7.158 total
gus@ocean 0 0 ../rank_speed_test% ./test 314159 1
generating random queries ...filling compact dynamic
Elapsed time: 1.35888s
Elapsed time: 6.41567s
sum = 49688700
./test 314159 1  8.84s user 0.20s system 99% cpu 9.034 total
gus@ocean 0 0 ../rank_speed_test% ./test 314159 0
generating random queries ...filling sdsl
Elapsed time: 1.61963s
Elapsed time: 5.03132s
sum = 49688700
./test 314159 0  7.83s user 0.21s system 99% cpu 8.041 total
```

That is filling is much faster, summing is same speed.

**Comment by rob-p** [comment]
Hi @gmarcais,

  Sorry for the slow reply.  I was away on vacation at the start of the week.  This looks awesome!  I'll try out your changes in my benchmarks and let you know how it looks.  Overall, it seems I'll be able to replace SDSL with the Guillaume vector :) 👍 .

Edit:  Looking good!

```
rob@newton:~/rank_speed_test/build$ ./src/test_bv 4000000000


 Statically Sized

generating random queries ...filling vectors

sum sdsl (new)
Elapsed time: 3.88727s
Elapsed time: 3.89681s

sum sdsl (old)
Elapsed time: 3.18204s
Elapsed time: 3.17212s
sum 1 = 380648897

sum compact (new)
Elapsed time: 3.8091s
Elapsed time: 3.7687s

sum compact (old)
Elapsed time: 3.07279s
Elapsed time: 3.06671s

sum 2 = 380648897

sum std (new)
Elapsed time: 1.98394s
Elapsed time: 1.98603s

sum std (old)
Elapsed time: 4.6879s
Elapsed time: 4.71232s

sum 3 = 380648897
```

No idea what `std::vector<bool>` is doing under new-style for loops, but compact looks like it's everywhere comparable to (or beating) sdsl!  However, the results under clang still astound me a bit:

```
rob@newton:~/rank_speed_test/build$ ./src/test_bv 4000000000


 Statically Sized

generating random queries ...filling vectors

sum sdsl (new)
Elapsed time: 5.22749s
Elapsed time: 5.23109s

sum sdsl (old)
Elapsed time: 2.27268s
Elapsed time: 2.23961s
sum 1 = 380648897

sum compact (new)
Elapsed time: 8.84093s
Elapsed time: 8.8241s

sum compact (old)
Elapsed time: 2.23277s
Elapsed time: 2.23155s

sum 2 = 380648897

sum std (new)
Elapsed time: 4.45914s
Elapsed time: 4.37528s

sum std (old)
Elapsed time: 1.89839s
Elapsed time: 1.90233s

sum 3 = 380648897
```

There's also the question of how things look for int sizes > 1 bit (sdsl specializes for native type sizes --- so 8, 16, 32, 64), but maybe that's a different test?
